spring:
  h2:
    console.enabled: true
  profiles:
    active: DEV
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
  jpa:
    properties:
      #      javax:
      #        persistence:
      #          schema-generation:
      #            create-source: metadata
      #            scripts:
      #              action: create
      #              create-target: create.sql
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
